services:

  infomail:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8028:8028"
    networks:
      - cicd_default
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t

  client:
    build:
      context: D:\Study_JaBa\Infomail-frontend\
      dockerfile: Dockerfile
    ports:
      - "8027:80"
    networks:
      - cicd_default
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t

networks:
  cicd_default:
    driver: bridge

  #  mailhog:
  #    image: mailhog/mailhog
  #    restart: always
  #    logging:
  #      driver: 'none'  # disable saving logs
  #    ports:
  #      - 1025:1025 # smtp server
  #      - 8025:8025 # web ui
  #
  #  database:
  #      image: postgres
  #      ports:
  #        - "8034:5432"
  #      environment:
  #        POSTGRES_USER: infomail
  #        POSTGRES_PASSWORD: infomail
  #        POSTGRES_DB: infomail
  #      networks:
  #        - infomail-net