server:
  port: 8028

logging:
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  file:
    name: logs/infomail.log
  pattern:
    dateformat: yyyy:MM:dd HH:mm:ss |

spring:

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.useProperties: true
      org.quartz.scheduler.instanceName: quartzScheduler
      org.quartz.scheduler.idleWaitTime: 5000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/infomail
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    path: '/api/v1/api-docs'

application:
  timezone:
    default: ${INFOMAIL_DEFAULT_TIMEZONE}
  email:
    sentFrom: ${MAIL_EMAIL}
    confirmation:
      tokenLink: ${INFOMAIL_FRONT_REG_LINK}confirm?token=
      subject: InfoMail - email confirmation
    rejection:
      tokenLink: ${INFOMAIL_FRONT_REG_LINK}reject?token=
  security:
    secret: ${INFOMAIL_SECURITY_SECRET}
    frontUrl: ${INFOMAIL_FRONT_URL}
